#!/usr/bin/env python
"""
Shapefiles...
Save typing/clicking when moving/renaming them
"""

import click
import os
import shutil

@click.command()
@click.argument('infile', nargs=1)
@click.argument('outfile', nargs=1)
def mvshp(infile, outfile):
    """
    mv a shapefile

    mv a bunch of shapefiles with this syntax:
      `$ for i in *.shp; do mvshp $i shapes/$i; done`
    """
    # trim file name extensions in case we're receiving them
    infile = os.path.splitext(infile)[0]
    outfile = os.path.splitext(outfile)[0]
    for suffix in ["shp", "dbf", "shx", "prj", "sbn", "sbx", "shp.xml", "cpg"]:
        if os.path.exists(infile+"."+suffix):
            shutil.move(infile+"."+suffix, outfile+"."+suffix)

if __name__ == '__main__':
    mvshp()